# Mémoire allouée à Gradle pour la compilation
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX (obligatoire pour ce projet, qui utilise androidx.*)
android.useAndroidX=true

# Active la mise en cache des builds Kotlin
kotlin.code.style=official

# Non-transitive R class (recommandé par défaut sur les projets récents)
android.nonTransitiveRClass=true
